const REWARDS = Object.freeze({
    SPORTS: "CHAMPIONS_LEAGUE_FINAL_TICKET",
    MUSIC: "KARAOKE_PRO_MICROPHONE",
    MOVIES: "PIRATES_OF_THE_CARIBBEAN_COLLECTION",
    KIDS: null,
    NEWS: null
});

const ELIGIBILITY_STATUS = Object.freeze({
    CUSTOMER_ELIGIBLE: "CUSTOMER_ELIGIBLE",
    CUSTOMER_INELIGIBLE: "CUSTOMER_INELIGIBLE",
    TECHNICAL_FAILURE: "TECHNICAL_FAILURE",
    INVALID_ACCOUNT_NUMBER: "INVALID_ACCOUNT_NUMBER"
});

module.exports = { REWARDS, ELIGIBILITY_STATUS };
